I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 301, in script
    K "C'est bon j'en vois un qui a l'air pas mal sur google."
Exception: Sayer 'K' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 301, in script
    K "C'est bon j'en vois un qui a l'air pas mal sur google."
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'K' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.5.1648
Friends Trip Netherlands
Sat Jun  5 23:54:17 2021
